def solution():
    seq = "TGGCTATTCGGGCGTAGTATACATAGAGGCTACCGATGTCGGGAGGATCCATGCGACAATCTTTCTCGCAGCGTTCACGTCAGCCCGCAGAGGTACGTGTAAACAAAAATTTGTATGCCTAATGGGGTACGAATTCGTACGATGTGCCCGGATACCTGTTCTTCTGCGTTGCTAAGATCCTTACTTCTACTCTGGACAACACAGGAATTGCTGGTGGATAGCTATAAACACGTCCTGCTTAGTAAATCATACCCGCTGTTAACATATGCTGCTTACTACACATTTCCAAAAGAGTATTACTCTAGTAGCGATTCTATGGAACGTCATATCCAAATTAACCCATTGTTGATTGCCGGCTCGGATTACGTACTCGTCCTGCTAACACACGGCTACCTGATCAAAAACAGAGGCAGGCTCCCTTTCAATGGTCTCGGGGCGGCCCTAGGGCCCTCCACGCGGGGGACCTGCATTGGGGGTGCATAACTTCCTAGAAGAAGTTATGGGACGCCACATGCCTTGGGAATATTACGGAGTACGAGTGAAAAGGGTAAGCGATCTCTGGGGCGGGACGGCTCGTCGTTCGAATCATGAGCCGAGGCGGGCGGGGATGGACCGCACCGCAGGAGGCAGAGCCTCTTTTCCCTTTTCAAGCTCTGAGGTTTTCGCAGAGCGATTCGTTAGTAGAATGAGCTAGTCAATTGGTAAATTTAAAGAAATAGTCGAGTTCACTACATCTTGTAGGCCGCGTGCAAGAGGGCGGTCTCCAACTACCTAAGTCGGATGAGGGTGTGGCAGTGTAGATGGAGTCCTATGATTGAGAACCTGGACGCCAGTCCCATGAAATTCAAGGAAAAGCGTGTGGGTCAACGGTCCCAGCGACACGTGCTGTTCGGCTCGGTGCTTGTTACGTGGGCCGGCTAACAGCCTACGATATCGGCGTACCATCGTTCGGGTCTTT"
    ans = [0 for _ in range(4)]
    for c in seq:
        if c == "A":
            ans[0] += 1
        elif c == "C":
            ans[1] += 1
        elif c == "G":
            ans[2] += 1
        else:
            ans[3] += 1
    return ans
print(solution())
