def minDistance(word1: str, word2: str) -> int:
        l1 = len(word1)
        l2 = len(word2)
        dp = [[None] * (l2 + 1) for _ in range(l1 + 1)]
        for i in range(l1 + 1):
            for j in range(l2 + 1):
                if i == 0 or j == 0:
                    dp[i][j] = max(i, j)
                    continue
                if word1[i - 1] == word2[j - 1]:
                    dp[i][j] = dp[i - 1][j - 1]
                else:
                    dp[i][j] = min(
                        dp[i][j - 1] + 1,
                        dp[i - 1][j] + 1,
                        dp[i - 1][j - 1] + 1
                    )
        # print(dp)
        return dp[l1][l2]

from helpers import parse_fasta
def solution(input):
     s1, s2 = parse_fasta(input)[1]
     return minDistance(s1, s2)

print(solution('''>Rosalind_2591
PITKEYQNHLADSAWRTGREFQRKQYLIRKKLRCNGSIQEHGAEAQKWSPFNMHQYRQFF
GWTRQTSPQTRPCSLEYTWDGRIAGLTYTGAIQFQNDWFCSFMMWAGFCKETMDPTFNCD
PYCLRYSQCAPKTGCAENQDFIATSFREDSLQNHRWPVMQEIIQQHVIETGEMCKYPPLS
QIASEEMRARWQILHVDQSRQAHAMINTYHQRKTKMRKSHRMYNFQSDESCAAKLETCAV
PGINIRLWYWFMLDWCYMMMKPEAKHHYGSYALMGMFARHMCYEPNRTVDNNTYWTKQGC
KLGSREGEGIHQKGQHVSERMAHTSAGKCSPVWMPLWNDLMTCVWELWMNDNVLSDGCAI
KAMWSHPYVPEQAVQLSFHSSKYEDRRLAQSCSDCQVMCDSINDPKVYQMTMWSSIRMIN
WVWSHMYLSWRSPYCRWMSGVYKNKLLKGQPYQKFKFNIHPYCTPIYHKIEGMEPKKPDC
QGWKPVDTHKDFEARVRWIIHNYDDNIIFHRNSMYIMWISGVMCVDGIHNSHYSGEPDLY
IHVFWNFYDIGYCVVGNRAYKCVYTWWETYCSSYDINVPYGPIGMSMFCSWEDHYTWEYV
LCMKMMFAINQNIFKYFEHKVRRTIGMIWGALDEIALYFLFCEDMKALLCYNIAVLLPQD
MIIVQGAKTVTGTDTAIFRRRMQITCHTKKHVMFNKNWHEDRPIKAPGAFWQIVTMCQKT
HCFGEIVTAPIHPDATSDNGLDTWYFIDYYCWKNEAHGHHHKLGEPFPKWWQYIWSEMNR
KMTNDVAYNEHFTFKVVQMNGQLRAPSPAPYKKIDSFHYEITDDENW
>Rosalind_5824
PITKEYQNHLSAWQGTWDSNFNVSREMNRQDFQVWKQMKDDLIRKKLRCNKSKGEHSWVY
TPEIQKWSPLNMHQYRQFFGWTRQTSWDGYIAGLDYRGSIQFQNDWFCSFMMWAGFSCET
MDYCLRYSQCAPKTSCYENQDSLQNHRWPVMQIQQHVIMTRYGEMCCHFNVYPPLSQIAS
EEMRGTGQIQTHVDQSKMRKSHQMYNSESCGWRELCDAKPADQCKLTTISWCCNYCNAVG
EINIRLWYWFVILDWCYMIKHHYCQYHMCYEPNRTVDNNWLICEINYWTKQGCKLGSRGQ
HASERMAHNQWQCFHRCRKCQQQHWDNVLPDPCFILGLDTMRDDQCPMMTWMSGLSHVYV
PEQAVIRSFCSHCQVMCDYEMTMFRMINWVWNWVKQHGHMYQSWRSPYCRWMSGVQPYSN
ALPEMSIRREYHKIPGGMEPKKPDFLPAYVPFDCTKWDYSHKDFEARVRWIICNYWFHRN
SMYIMWIHQLIQNIHNKMFKQDRPFELCFHWNIGYCYTPEYLVGKVGNRAYKCVYTWWEP
MQTHLDKYCSSYDINVPYGPKIMSMFTPNWNSWEDHYTWEYGCPAINQNIFDTQQDLSYF
EHKVRRTIHIWGALDETFLAKYRPHWHHIAFQNCFGHLMFWEDMKALLCYGAKTDTAIFR
RRMQITQCGMQKYSVMFNKNWHEDGNHVNYGQRVGEIVTAPIHPTSDNGLDGILYYSKEK
RRNEAHGNHHKLGEPFPKWWQYIWLYKREMNRACRAYNEHFTFKVGWMFGQLRAPSPHLA
MPYKKIDSFHYEITDDENW'''))