from helpers import blosum62

GAP_PENALTY = -5

def maxScore(word1: str, word2: str) -> int:
        l1 = len(word1)
        l2 = len(word2)
        dp = [[None] * (l2 + 1) for _ in range(l1 + 1)]
        for i in range(l1 + 1):
            for j in range(l2 + 1):
                if i == 0 or j == 0:
                    dp[i][j] = max(i, j) * GAP_PENALTY
                    continue
                else:
                    dp[i][j] = max(
                        dp[i][j - 1] + GAP_PENALTY,
                        dp[i - 1][j] + GAP_PENALTY,
                        dp[i - 1][j - 1] + blosum62[word1[i - 1]][word2[j - 1]]
                    )
        # print(dp)
        return dp[l1][l2]

from helpers import parse_fasta
def solution(input):
     s1, s2 = parse_fasta(input)[1]
     return maxScore(s1, s2)

print(solution('''>Rosalind_7214
CQNMILITTSCFNWMCRNGFLCAFIGRLNNASNWVNICCEHGVFKSCFRSEYGSGITYGS
ENKHDHWTNTLQTHDDQDCGKRIQHANGADQRGAFRWPWPLSGASKLQDWTLFNMCQFML
VHFDNQLIMGFPWETWIRYWIMNTTCGNGQDASEVSWFLGCTPLMQCRDAVVHFHNLHRV
GIPMMVFSCSHPIFNDRGYSCCMMHIDRWKKCRRYMYLNMWECVDSPRTDMEIERPWNNP
LCYNCSWRRGRFDHKMIPYFHWRDPFKENAVVDNFFKMDEASWLLHPKGVNMLCGSHEMC
STVGIIKAIRNGALSFQEGKEYLCNWDYDAYLNMMWQPQHCHSQTEFPFMYPKNLQSFMA
TQLNDHHEAPCEYAEQFYRSYPACFSSNGKNSHTAWVSTFQYWLPWHHGLDYFDICYMQI
WYNWDPGFQKGTPAVPPRQQWPSCWDYWETTMEWFMDDATMCHQACNNDQWSCAHSSYGQ
QLEQGWCLLEMGKVWKSEIKNRIDSQGQEQIDISYSSRRRYAGNVSNHCQTHQEPSAWWR
PTPQPKRDFKCVIAEEPLRYRKQECHDLCCCHETHFAANIGFHLDFGRGCFHSEWPKNEC
QWAMGCKSRLVVYVLGCNMPCIYDGAMGICDQNQYDYTTDIHFHPCPSLFHGQGENPYDM
NYNSNYVPERMYCCIVETPMAPPPCIYYNMVIGAQGQTSYKYHGQNVHEPEVCCTKWINM
NTETANRPQSFIRSPARRLSTGPAIAHGEWCHFTHHATMAIRPYYVITSLGQPVHMISLA
IPQIDHFWGEHKCRSGFHANEFERISDWHEHDPQCGVMNHQSTES
>Rosalind_5454
CVCHSNREGVRNGNNYSSWVRICCEHGVFKSMWSEYGSGITYGEENKHMHAHNVMHWTVQ
MYTQTHDDQDCGKRIQHANGAGLSKLQRKQQFFEKCWTLFNMTQFMLVHFDNQLINTIIY
LCGNEVSWFLGCTPLMQCRDAVVHFHMVLRMKCLHRVHSQKEYSIPMMVFSCGHPIFNDR
GYSCCMMHIDRWKKCRLYMYLNKFRCEWAFKGYMTLACVDFPRTDMEIERPHNNPLFQPQ
FGMYNCSWGRGRFIHKMIPYFHWRDPCKNAVVDNFTKMDPASWLGPHPCVAHPKSVNHEM
CSTVGTCYIKVIEFCANHIPRWMFFPSCNGALSCTFGHKYRHNMQPHFWKMGPKIVGYGQ
STLDSFMATQEQAWKKPDNQSEDISDHHEPCVYGCMCHSQFYRSHPACFSSGGKNSHTAW
VDPNPSNTLPTIHGLDFDICYIWYNWDPDFQKGTPAVPCKQRQPWPSRVKGGHWWHWDYE
WFMDDATMQHQYCNNDCAHSNTWSHYGQQLEQGWCLLETECTHYEAVWHINICCSEIKNR
IDSQGQEGIQISYSSRRWLGGNVSNHCQTHQNWPAMYCSAKTCMSKRDFCCRKQEETDFK
CWHHAVIGFFLDFGRGCFHSEWADTAGMTQGCKSALVVYVLRHSEFSACEFWSNDNRCEG
TVECVIRFFWYDGGICDQNQTDIHFHPCESLFHGQGENPYDMDWVRRNKQYLFLLWYSYE
PERMYCCIVETPGMFRKMNRSAPPWERPDVYCIYHNMWSSCEGAQGQTSYKYHKQNVHEP
AEKRWSQTKLINMNTEWANRPQSFYRIWTRSPARRLSTGPAIAHGPATVITSLAIPQIDH
FWGEHKCRWGFHANYFYGWDYMISDDPWDGWWPICGVMNHQSTES
'''))