amino_acid_codon_counts = {
    'F': 2,
    'L': 6,
    'I': 3,
    'M': 1,
    'V': 4,
    'S': 6,
    'P': 4,
    'T': 4,
    'A': 4,
    'Y': 2,
    'H': 2,
    'N': 2,
    'D': 2,
    'Stop': 3,
    'Q': 2,
    'K': 2,
    'E': 2,
    'C': 2,
    'R': 6,
    'G': 4,
    'W': 1
}


def solution(pseq):
    product = 1
    for aa in pseq:
        count = amino_acid_codon_counts[aa]
        product = (product * count) % 1000000
    return (product * 3) % 1000000

print(solution("MADSEKWSYYYEWYRIHTMSPREEDHQGLNRVPCSSVKPPCKRGNICGKESKYPGQSHISKKMICSMPCPFVMAASWINYPMPSVTAIFGCNAIFYNYQVNLSDHQFFANSGPTCCVEKYAQRSPTKTEFTEWVKWWRIETIADPLQFLHTAVCQRSVADANVCTQVLTQRTRWICNPQDWVPQGDGGGPAGDCTITHTCTYAYDGAIQCVKRNFYMEQDREASTDSTYGRRDGYPSVKFNVWDKCAHVHYCDNQQEAPSIGNRVTDNSDILVCSVLQKWRDYEHTHITMYKPHENINLRHDMVGWAVMRAEWPRMAPCTYPYMYTSQLAASIYLRLIDGMWGWKGKWLAPLYPGPHPSGYVRQMHTEVADGPCNGMIFYRIGFMFSNHRPGKYFRAGRNIFSHCILCYCYQFNATHENCWGFGWFQRDPAVICLKTSKWTWPHLRGAPPFGEMGTWYLDVTFNPMYGWELPHNGNKRDHQTYYCYFIWCRCEGWKWGNIYTHQTCPNDEHIRKKFVVYHEVVKDHLIRVDIDWFNNCTVLCFQFLVESHCQSVTCLRMHQLRNVHFCDVGVYQHGIDLHNICETCHNGLKRRMNTNCILTDSQYYPDPMWWHRKSMMWHPFIINPWGKNWMAPCRVYSHNYRPNPSPDQFKKKTLFFRFHLGITATNMYWSPVKTMMMCVEVTIRCRYRQNSKRKQPGSHGINKYTIEYHLHYPLYIYYPNHCNKGCVGFNQHHELKTWFRDFFVAVIGPFMVYAKRKAFWDVDHRFMALNCAYGDYQSPEAFTLEMDCFINYRMYPYLWIHPYDNCWSQEMPDMAYEDKGDEWWPKTFCGMQRGYQCWQSNQGKYCFLMRAFFCPQMMMKRVFYDHFTPIEMRDKQRMVYVINWIIHYDVGITSVKRVGVVEDWPKFAVWTYLYTEVRGVEWDCQCIPHTKVLTEVALQIGWVEYWVMLRIVTNMMICGQNPTELYQEHYIVFFVEANVWCVEPMKGCTWAERTVDY"))
