def reverse_complement(dna):
    # Mapping of each base to its complement
    complement = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}
    
    # Generate the complement sequence
    comp_seq = [complement[base] for base in dna]
    
    # Reverse the complemented sequence
    rev_comp = ''.join(reversed(comp_seq))
    
    return rev_comp

# Example usage
print(reverse_complement("CCTATTACTCTCTCTCAATACCAGTCTCCAAAACACTTAGTCACGGTTGCCGTCCAGCTCCGAATCTCGCGACATACGGCTAAACTAGTCTGGGGCGGATGTTCTCCAGACCCCGTGGTCCTCTTAGCGACGAGAGGCCCACCAGAGTGCCTCTTGATGAGGCCCGGGTAAGCATTGGCCGCTGAGTATAGTTGGCTAATCTCGAGATTTGAAATGCCCGAGAGTGATCTACGATCTATTCCTAGGTCAAGGGAAGCGCTTCTCAAATGCGGAATTCCTGCACCTATATCCTAACGGGCATCTCCCCTAAGCCTATATAAGATTGTGCTAACTACACATGACCTAGGCAAGGGGCCACTGTGCTTTATCCAGTGTAAATCAAGCTGGTCGAGTTGAAACTACGACGCGCAGTGTTGTACCCAAGCGCCTCTTTGACATATATCCTTAGATAGGCGACGGTCTAGGAGATCCAGGGTTTCACTACGGCGGGATGTTCACAGAGGGAGTGCAGACGTGACGCTGTCGCTGTCTGAGGAAGATGGCCCACCCTCTCGGCCGGCACCTGTCAGAGGTGTTAGGCCGTGTCCGGATGACGTTTAAGAGTTTGCTCCCCCCCTGGGTAATAATTAAAGTGCACGGCTTAGTCGCCGCAGAGATTCTATCGTTGTTCAGGGTAATCTGGCACACCTTCGTTCTTTGTTAGCAGTGCTCGTCGAATTGCCAGACCGATGGAATATCCCAGCCGTGAAAACGAACTTAGTCAAGTCTGACTACTTATGATGTTAAGTTAATGGTCACGTAGCTGAAAGTTATTGTAATGATGGCGTCTGCAAGAGTGAGACCCT"))
