complement = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}
def check(seq: str) -> bool:
    revc = "".join([complement[base] for  base in reversed(seq)])
    return revc == seq

def solution(s: str):
    s = "".join(s.splitlines()[1:])
    for i in range(4, 13):
        for j in range(0, len(s) - i + 1):
            seq = s[j: j + i]
            if check(seq):
                print(j + 1, i)

solution('''>Rosalind_8179
GCGCTAACGGAGTCGATTGGGTAACGTGAACGTTACATGACTCATGCGCGCTGGTATATT
ACCTTCGGCTGCAGGGAAGACGTCTGCGGACCTAATGGGTGTTCCGCTCAATCTGGATAC
TCCCTTGAAGAGCCAACAGGGCTCGTTAGGGCTAAGACGGCACATGAAAGCTTCCTAAGT
AGGCCACCGTGCTTCGCGGCGACTATCCTTCCGTAGATGTTGCGTTTATATCCTCCGCTG
TTTCCTTGCAACAGTAGTTGGCCTCTCACCATATACTACGGAATTGATACACCCAGTGGT
CAATGTGCGAGCGTCGTTATTGAACCAACCTTACATTAGAGGCGCAATCTGCCAAGTGTG
CGACACTCCGCCCTTACTATCTAATCTGAGGCGTGCATACCAATAAACTGCCTATTTACG
CTTAATGATTGAAAGAAATGAAGGCTGGGTATTGCTTTCGGGGACACAAAGGCCACAGGA
CAGTAACGATGCGCCGGCGCAACGCCCACGGCGCAAATTCGTTGTAATAGTAGATTGAGA
GTACAAACCTCGGGACACAGGCGCGGGTTATTCCAGGCGCCCATTTTGCGTGTTCACATG
CGCGGGGCGAAGCACAGCACGAATGTCAGACGCAGGTTTCGTTTTACCCTCAGGGCCAGG
CCTGGCACGAGATTTCTCTGAGGGGCGTCTATCTCTTTTCAGTGCAGGACGGTAAGGGGA
CGACTGGATTGATGTGAAAGACAGAACTCACGGCTACGCAAAGCGATATAGGTCATAGAT
GGCCGCAAGCGACTTGTCCGATTAAGCTAGCAGGAGAACTTTCACGCTCGACCACGTCAT
AAGCATTCGGCGAGTTACACGAGGTGATGACATCTTACCAAGGTCAGGATGTAATGCCGG
CCATCTTTTACAGATATAGGCTTAGCTCCCTCATCAATTGCGAAGATGAGAGGAATTGAG
GCGGAAAGTAGGTCACTTACTTTCATCGCG''')