import helpers

def solution(input: str):
    seq, target = helpers.parse_fasta(input)[1]
    i = 0
    result = []
    s = ""
    for targetBase in target:
        while seq[i] != targetBase:
            i += 1
        result.append(i + 1)
        s += seq[i]
        i += 1

    print(*result)
    print()
    print(s)

solution('''>Rosalind_4249
GAGAAATTAGAGTCGAGTCGCAGGCTCCCTGTACTGCTTATCAGTCCTCCCAAGTTATTT
CAATCCAGAGGAGTACGAATGGATTTCGACAGACATTTCCGTCCCATGGGTTAAAGGGTG
GACCAGTAATACTTTGTGGCGCGGAAGACGGAGCGGAGCCGGGCTTCGGCAGTATACGTT
AGTAATGATGGACGGCAGAGGCGAATATTGAGTCGTTAGGGGGTCCCCTAAATAACCCCA
AAGAAGTATCCTTCTTCAAGAGAAACAGCCAAGGATGTAAAGAGGGTCGCACCCATGCAG
GGCTAGCGGGTGTCTAACTGAAACGTGTAATGCTGCAGCACAGTCATTCCCTGTTTTTTA
AAGTAGATCGTGGGTTCGACCTTTCAGTTCCATATACTGCACGAAGTCGCCGTCAGGGGG
GGCGGCATCGGGATGGAAATACCAGCTTAAACAGCTTTAAGGCGTAACCACCTGCCCGGA
AGGAACTGTACGTCAAAGAAGTGGAAGAGGCATTCGACTTTGCCACGTTCAGAATTGCCC
TTGCGCACGCGCAAGTTGGGCTTGGTTTTCGCCAGAAATATCCCTATATATTCGACGTCG
CTCGGCGCCGTGCCTCCCGTGTTACCTCACCCAATGGGCGTTAACATTCTCAACATTGGA
GCAGGCGACCAGCAACCATAGCAGGGCGAAGAAAGAATCGAGTGCGTTCGGTTATCTCGT
AACCCCACTGGATCTAATTCGATCGATAATCACCTCAAAACTCGATGCCTATTAAAAGTG
ATTACCCCAGCCAGGGGATTGAGCCGACGGATTAGCCTGGCAAGAAATCATGCCAGTCTG
CACAAAACTTGATCTTGAACTCCTTCTAGAGTCCCAGTACGCTTACGACTCTCCCCATGA
CTAAGTAGTAAACTGTAAAGTCCTTGCAAGGTCGGAATGAA
>Rosalind_4384
TACCTTGTAATAT''')
