def solution(s, t):
    repeatLength = len(t)
    result = []
    for i in range(len(s) - repeatLength):
        slc = s[i:i + len(t)]
        if slc == t:
            result.append(i + 1)
    return result

print(solution("GCGTGCCGAGGGTGCCGATTGTGCCGATGTGCCGAGTGCCGATAGTGCCGAGTGCCGACGTGCCGAACACGTGCCGACGAAGTGCCGAAGGTGCCGAAGTGCCGAGTGCCGATGTGCCGAGTGCCGAGTGCCGAGTGCCGAAGTGCCGAAATCTGTGCCGATGTGCCGAGCGTGCCGATGTGCCGAGTGCCGAAGTGCCGATGAGTGCCGAGTCGTGCCGATTGTGCCGAGTGCCGAGTGCCGAGGGTGCCGAGGTGCCGATAGTCGTGCCGAGACGTGCCGACGTGTGCCGAGTGCCGAGTGCCGAAGTGCCGATGCAGTGCCGAGTGTGTGCCGAGCGTGCCGACTCGTGCCGACGTGCCGATGTGCCGAAGTGCCGACGTGCCGATGTGCCGAGTGCCGATGCGTGCCGAGTGCCGATAGTGCCGACGCCCGTGCCGAAAGTGCCGATCGTGCCGAGTGCCGAGTGCCGAGCTGTGCCGATTTGTGCCGAGGTTCTTGGAGGTGCCGAGTGCCGAAGTGCCGAATAAGTGCCGAGTGCCGACAGGTGCCGAGCGTGCCGAACGTGCCGACTGTGCCGAGTGTGCCGAGAGTGCCGAGTGCCGAATCCGTGCCGACACCCGGGTGCCGAAGTGCCGAATGTGCCGATCGTGCCGAAGTGCCGATAGTCGGTCACCGTGCCGAGTGCCGACGGTGCCGAGTGCCGAGTGCCGAAGGTGTGCCGAGTGCCGATGTGCCGACGTGCCGAAGGTGCCGAAGGTGCCGAAGTGCCGATGTGCCGAGTGCCGAGTGTGCCGACCGTGCCGAGCGTGCCGAGCGTGCCGAGTGCCGAGGGGTTCTGTACACATGGTGCCGAAAAGGTGCCGAAACATGTGCCGACGTGCCGACAGTGCCGA", "GTGCCGAGT"))

print("29, 45, 99, 114, 121, 128, 180, 205, 224, 231, 287, 294, 320, 390, 407, 453, 460, 505, 531, 575, 593, 678, 694, 701, 719, 776, 783, 819".replace(", ", " "))

