import helpers

def solution(input: str):
    s1, s2 = helpers.parse_fasta(input)[1]
    transitions = 0
    transversions = 0
    transitionPairs = {"A": "G", "G": "A", "T": "C", "C": "T"}
    for i in range(len(s1)):
        if s1[i] == s2[i]:
            continue
        if transitionPairs[s1[i]] == s2[i]:
            transitions += 1
        else:
            transversions += 1
    return transitions / transversions

print(solution('''>Rosalind_5172
TTCGGAAAAGATACATTAAATTATCCTGGTCATTTGGCGCGAATTGTACGCTTTCGCCAA
GTCTCCTGCCGTGCCTTGCTCCATACCTTGTCACTTCGGCGTTCCCACTGCCTCGGCAAC
CGAGTGCAAGTAAGCCTGATAATTGCGAGCTTATTTGCCAGCCATTTCACCGCTCTGGAG
CCACTCCCATTACTCGTCGCACATGGGCGAGCTATTAGGGGATTGCATGCCCATACTGGA
GGTAAAAGATCTGTTCGGAAAAAAGCTTATAGAATTATTCACCCGTTCCTTTTAACGTCC
ATACGCCCTTTATGCGTGTGCCGGTATCACCCCTCCCAACCCAGGACAGAGAAGATTGAG
AGCTTGCGCCCGATATCTCACGACGCAGGACGCACAACCACAACGATTTGCACTGATGGT
ACTCCCCAGTAGACCTATTCTGAGGGCATCTCAAGTAGTGCTAATGCTGCTGACCCGTGC
GTTTTTTTCGGGTTCGCTCTGTTGTCATATCCTAGAGCGAGGAGGCCGAATTCGTGCCGT
CACAAGCAAGTTGTAGTGTTAGCGCGAGCACCACTGCACACTCCGCGTTCCAGTCCGACC
GTGGGTCTAGCTTTAACGCTTAAGGATATCGGGTGATTAACCGAATAATGATTTAGGTTC
TGGACGACATAAGAGGAAACAGGCTTTTTACAGGAAAGATAAGACGTACGCATTAAGATC
ATAGGTCGGAATGCGTTATCCGACGCTCTAAAAACGAGCCCCTCCTGCTATTATGAACGA
GAGCTTATGGGTTAGGTGATATAGCGGGCTTGCCTTTGCCCCGTAATAGCTGGATGCTCG
CGCTTCTTGGGAGTGTGATTACTAATCAATGGTGCCGTTCACATAAGTTACGTCTATTCC
CGGCTCATCCACTATT
>Rosalind_2687
TACGGAAGGAACCTACCAGGTTATGCGGCTCACTTAGCGGGCATTGTACGCTTTCGCCAG
GTCTCCTGCAGTGCCCTGATCGATACGTCGTCAATCTGGAGTATCTACTGCCCCGTCAAC
TGAGCGCAGGTAATTCAGACAGCTGTGAATTTATTTCCCCGCCATTCCATCGTTCTGGTG
CTGTCCCCATGAGTGGCCGTATGCGTGTCAGCCGTTAAGGGATTGCATGCGCATACTGGA
CGTAAAAGATCTATCTGGGGAAATGCTTTTAAAATCATCCCCCCATTTTTTTTAGCGCCC
GTACGACATTCATATATGTGCCTGTACTATCCGACGCAGCCTTAAACAGAGAAGGATTAC
GGCCTGTGCCTGGCATTTCACAACTCAGGGCGCACGACTACGGGGATTCGCGTTGAAGGC
GTTCCCTAGTGGGTCCATTCTGAGGCTATCTCGGATGGTACTAGTGTTGCCTAGTTGATG
GATTTCTTTGAGCCTACTCCGTCGCCTTACGCTATTGTGAGGGGGCCGGGTTTACGTCGT
TACCGTCAAGTCGTAACTTTAGTGCGAGCACGACTGTACATTCCGTGTCCCAATCCGGTC
GCGGGTCTAGTTTTATCGATTAGGAGTATCGAATGGTTAGCTGGGTACTGGTATAGGGGC
GGGATGGCATCAAATGAAACAGGCCCTCTAATAGAGACGTAAGAATTACGCGGAAACATC
ATAAGTTGGAATGTCCGGCTCAACCTTCCAAAGACAAGTCTCTCTCGCGCTTATGCGCAA
GAGCTTATGTGCTACGCGGTACGCCAGGCTTCCCCTTGTTCCCGAATAGCTGAGTACTCG
TCCTTCCCGGGAGTGTAATTACTATTCCATCGTACCTATCACGTAAGTTATGGCTATTCG
GGGCTAATCTGTTATT'''))

